/* ============================================================
   PENGATURAN WEBSITE NETIES
   File ini dihasilkan oleh Panel Admin (admin.html).
   Jangan diedit manual — gunakan Panel Admin agar aman.
   ============================================================ */
const CONFIG = {
  "name": "Neties",
  "wa": "6281315100690",
  "area": "Surabaya & Sekitarnya",
  "def_msg": "Halo, saya melihat website Anda dan ingin bertanya.",
  "email": "neties136@gmail.com",
  "ig": "netiesyamsibar",
  "fb_name": "Netie Syamsibar",
  "fb_url": "https://www.facebook.com/netie.syamsibar",
  "hero_badge": "Siap Melayani Konsultasi Gratis",
  "hero_lead": "Halo! Saya <b class=\"agent-name\">Neties</b> — agen resmi asuransi <b>Prudential Indonesia</b> sekaligus konsultan produk <b>COWAY</b>. Saya bantu Anda memilih perlindungan finansial yang tepat, sekaligus menghadirkan air bersih &amp; udara sehat di rumah Anda.",
  "t1n": "100%",
  "t1l": "Agen Resmi Terdaftar",
  "t2n": "1-on-1",
  "t2l": "Konsultasi Personal",
  "t3n": "Fast",
  "t3l": "Respon WhatsApp Cepat",
  "red_desc": "Perlindungan jiwa, kesehatan, dan penyakit kritis untuk Anda dan keluarga — tersedia konvensional maupun syariah.",
  "red_li1": "Santunan rawat inap & penyakit kritis",
  "red_li2": "Perlindungan jiwa hingga usia lanjut",
  "red_li3": "Perencanaan warisan & dana pendidikan",
  "blue_desc": "Penyaring air, penyaring udara, bidet, hingga kasur premium dari Korea — tersedia skema sewa dengan perawatan rutin.",
  "blue_li1": "Air minum murni langsung dari dispenser",
  "blue_li2": "Udara rumah bebas debu, virus & bau",
  "blue_li3": "Coway Heart Service — perawatan berkala gratis",
  "about_p1": "Saya adalah agen asuransi <b>Prudential Indonesia</b> dan konsultan produk <b>COWAY</b>. Awalnya saya bergabung di industri ini karena satu keyakinan sederhana: <i>keluarga Indonesia layak mendapatkan perlindungan terbaik dan gaya hidup yang lebih sehat.</i>",
  "about_p2": "Bagi saya, menjual bukanlah tujuan utama. Saya lebih senang disebut <b>pendamping</b> — mendengarkan kebutuhan Anda, menjelaskan dengan bahasa yang mudah dipahami, dan tetap hadir saat Anda membutuhkan bantuan klaim maupun servis produk.",
  "chk1": "Terdaftar resmi & berlisensi AAJI",
  "chk2": "Konsultan COWAY berpengalaman",
  "chk3": "Bantu proses klaim sampai cair",
  "chk4": "Konsultasi gratis tanpa tekanan",
  "p1_desc": "Santunan biaya kamar rawat inap, ICU, pembedahan, hingga perawatan sebelum & sesudah rawat inap di rumah sakit.",
  "p1_tag": "Rawat Inap · Cashless",
  "p2_desc": "Perlindungan jiwa jangka panjang yang bisa dipadukan dengan investasi untuk dana pendidikan anak atau pensiun.",
  "p2_tag": "Jiwa + Investasi",
  "p3_desc": "Santunan tunai besar saat didiagnosis penyakit kritis — dari tahap awal hingga lanjutan — agar fokus pada pemulihan, bukan biaya.",
  "p3_tag": "Santunan Tunai",
  "p4_desc": "Pilihan perlindungan berbasis syariah dengan prinsip saling tolong-menolong, serta perencanaan warisan untuk orang tercinta.",
  "p4_tag": "Syariah Tersedia",
  "pru_note": "Informasi di atas bersifat ringkas dan bukan penawaran resmi. Manfaat, syarat, dan ketentuan lengkap mengacu pada polis masing-masing produk Prudential Indonesia. Saya akan menjelaskan detailnya saat konsultasi.",
  "c1_desc": "Air minum murni bebas bakteri, logam berat & kaporit — panas, dingin, dan suhu ruang langsung dari satu alat. Hemat biaya galon.",
  "c1_tag": "Best Seller",
  "c2_desc": "Menyaring debu halus PM2.5, virus, bakteri, alergen, dan bau tak sedap. Ideal untuk kamar bayi, penderita alergi, dan rumah di kota besar.",
  "c2_tag": "Anti Polusi",
  "c3_desc": "Bidet modern yang lebih higienis, hemat tisu, dan nyaman untuk seluruh keluarga — termasuk lansia dan ibu pasca-melahirkan.",
  "c3_tag": "Higienis",
  "c4_desc": "Kasur premium dengan layanan perawatan anti-tungau berkala — tidur lebih nyenyak dan bebas alergi setiap malam.",
  "c4_tag": "Premium",
  "perk1b": "Coway Heart Service",
  "perk1s": "Teknisi datang rutin untuk ganti filter & sanitasi unit.",
  "perk2b": "Sewa atau Beli",
  "perk2s": "Mulai dari cicilan bulanan ringan, tanpa kartu kredit.",
  "perk3b": "Garansi Resmi",
  "perk3s": "Garansi penuh selama masa sewa, teknisi resmi COWAY.",
  "perk4b": "Survei & Demo Gratis",
  "perk4s": "Coba dulu di rumah Anda — gratis, tanpa kewajiban beli.",
  "cow_note": "Harga dan promo COWAY berubah berkala mengikuti kebijakan perusahaan. Hubungi saya untuk harga terbaru, simulasi cicilan, dan jadwal demo gratis di rumah Anda.",
  "ecatalog_url": "https://ecatalog.coway.id/?hp=DST260101202",
  "step1": "Klik tombol WhatsApp dan ceritakan kebutuhan Anda — tidak perlu bahasa formal, santai saja 😊",
  "step2": "Saya analisis kebutuhan & bujet Anda, atau jadwalkan demo produk COWAY langsung di rumah Anda.",
  "step3": "Anda dapat rekomendasi yang jujur — tanpa tekanan, tanpa paksaan. Keputusan 100% di tangan Anda.",
  "step4": "Dari pendaftaran, instalasi, sampai klaim asuransi & jadwal servis rutin — saya dampingi terus.",
  "testi1p": "\"Awalnya ragu soal asuransi, tapi dijelasinnya enak banget, nggak pakai istilah ribet. Pas anak saya rawat inap, klaimnya dibantu sampai cair. Terima kasih banyak!\"",
  "testi1n": "Ibu Dewi R.",
  "testi1r": "Nasabah Prudential — Ibu Rumah Tangga",
  "testi2p": "\"Sewa water purifier COWAY lewat beliau. Demo di rumah gratis, penjelasan jujur soal biaya. Sekarang nggak pernah repot ganti galon lagi, anak-anak juga minum lebih banyak.\"",
  "testi2n": "Bpk. Andi S.",
  "testi2r": "Pelanggan COWAY — Karyawan Swasta",
  "testi3p": "\"Responsnya cepat banget tiap saya tanya-tanya. Pas jadwal servis filter datang juga diingetin duluan. Rasanya punya asisten pribadi untuk urusan rumah. Recommended!\"",
  "testi3n": "Ibu Maya W.",
  "testi3r": "Nasabah & Pelanggan COWAY — Guru",
  "faq1q": "Apakah konsultasinya benar-benar gratis?",
  "faq1a": "Ya, 100% gratis dan tanpa kewajiban membeli. Saya percaya edukasi dulu, keputusan belakangan. Silakan tanya apa saja — premi, manfaat, atau sekadar membandingkan produk.",
  "faq2q": "Berapa premi asuransi Prudential per bulan?",
  "faq2a": "Premi sangat bervariasi tergantung usia, manfaat yang dipilih, dan kondisi kesehatan — mulai dari ratusan ribu rupiah per bulan. Chat saya untuk ilustrasi personal yang sesuai bujet Anda.",
  "faq3q": "COWAY itu sistem sewa atau beli?",
  "faq3a": "Keduanya bisa! Skema <b>sewa</b> sudah termasuk ganti filter & servis rutin gratis dengan cicilan bulanan ringan. Skema <b>beli putus</b> juga tersedia bagi yang ingin langsung memiliki. Saya bantu hitung mana yang lebih hemat untuk Anda.",
  "faq4q": "Bagaimana kalau saya mau klaim asuransi nanti?",
  "faq4a": "Inilah bedanya beli lewat agen yang peduli 🙂 Saya akan dampingi Anda menyiapkan dokumen dan memantau proses klaim sampai selesai. Untuk produk kesehatan dengan fasilitas cashless, cukup tunjukkan kartu di rumah sakit rekanan.",
  "faq5q": "Area mana saja yang dilayani?",
  "faq5a": "Konsultasi asuransi bisa online dari mana saja di seluruh Indonesia. Untuk demo &amp; pemasangan COWAY, saya melayani area <b class=\"agent-area\">Surabaya &amp; Sekitarnya</b> — hubungi saya untuk cek ketersediaan area Anda.",
  "hours": "Senin – Sabtu, 08.00 – 20.00 WIB<br>(di luar jam itu tetap dibalas, agak slow response 😊)",
  "disclaimer": "Disclaimer: Website ini adalah website pribadi milik agen dan bukan website resmi PT Prudential Life Assurance (Prudential Indonesia) maupun PT Coway International Indonesia. Prudential Indonesia berizin dan diawasi oleh Otoritas Jasa Keuangan (OJK). Seluruh informasi produk bersifat ringkas — syarat, ketentuan, manfaat, dan harga mengacu pada dokumen resmi masing-masing perusahaan."
};
